# Generated by Django 5.0 on 2025-09-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="roommember",
            name="user",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
