global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'centrifugo'
#    dns_sd_configs:
#      - names: ['tasks.centrifugo']
#        type: A
#        port: 8000
#        refresh_interval: 5s
    static_configs:
      - targets: ['centrifugo:8000']